### ISSUE TITLE
usage of this plugin

### ISSUE THREAD

**Issue by erwanj** [damavis/airflow-pentaho-plugin#1]
Hello,

thank you for your plugin.
I have been trying to use it and have some question.
I am wondering how do you proceed with airflow when you need to run a job/transformation to reload historical datas. I have seen that it is possible to trigger manually the dag giving "Configuration JSON". Are you using this?

Thank you.

Erwan

**Comment by piffall** [comment]
Hello @erwanj 

We use to run all transformations with a date as an input parameter, so we use the command `airflow backfill`, check it out at official documentation: [https://airflow.apache.org/docs/stable/cli-ref#backfill](https://airflow.apache.org/docs/stable/cli-ref#backfill) 

It's recommended to stop the DAG before start the backfill in order to avoid duplicate tasks by the scheduler.

Thank you.
