### ISSUE TITLE
CarteTransOperator.expand_kwargs gathers incorrect log by map index

### ISSUE THREAD

**Issue by evgdol** [damavis/airflow-pentaho-plugin#29]
### Scenario: 
I have a transformation that should be run several times according to previous step results. I am using expand_kwargs feature to do this.
Simplified example:
`
t1 = CarteTransOperator.partial(
    task_id='tst_trans_params',
    pdi_conn_id='pentaho',
    trans='/public/test/tr_tst_input_params'
).expand_kwargs([{"params": {"PARAM": 1}},{"params": {"PARAM": 2}}])
`
The transformation tr_tst_input_params just outputps the input parameter into the log.

### Result:
All works fine. But the log for both map indexes gathers from the last parameter value only
![image](https://user-images.githubusercontent.com/126868762/227171812-0a780243-cbff-485b-8a72-7e2674e5a9db.png)
![image](https://user-images.githubusercontent.com/126868762/227172059-5a68575c-1be6-4a8b-a4dd-5c7b4c6b01b7.png)

On Pentaho side:
![image](https://user-images.githubusercontent.com/126868762/227172294-435dc5a0-5beb-483d-a6af-f0584adae158.png)
![image](https://user-images.githubusercontent.com/126868762/227172482-d0d45103-66a5-4e08-aad8-4096d89d5064.png)
![image](https://user-images.githubusercontent.com/126868762/227172670-a54661f4-2e42-4cd2-b952-f011abcaefc0.png)

### Expected result:
Log should be valid

### Environment
Airflow 2.5.1 + Python 3.10 + Pentaho server CE 8.0

**Comment by piffall** [comment]
Hi @evgdol ,

I found a limitation in PDI Carte server. Transformation run ID is not returned by the Carte server, so is required to ask the status and logs by transformation name. I guess that, as you are running both transformations concurrently, you are getting logs from just the second transformation run.

My recommendation is, wrap that transformations inside a Job, and always use `CarteJobOperator`.

I'll check if this can be mitigated somehow, but the error will always be possible because of concurrency.

**Comment by evgdol** [comment]
Hi @piffall,

Unfortunately, this was not helpful

**Comment by piffall** [comment]
Hi @evgdol , I have one question. Are you running both transformations in parallel?

**Comment by piffall** [comment]
Ok @evgdol . I recommend you to use those transformations inside a Job, and run using `CarteJobOperator`. That will work, because ID is returned correctly.

**Comment by evgdol** [comment]
Hi @piffall,

Thank you. Inside job it works properly.
